export const quizzes = [
  {
    id: "harmonic-field-c",
    title: "Campo Harmonico de C",
    description: "Perguntas sobre os acordes diatonicos da tonalidade de C maior.",
    questions: [
      {
        id: "c-1",
        prompt: "Qual e o I grau (tonica) no campo harmonico de C maior?",
        options: ["C", "Dm", "G", "Am"],
        correctAnswer: "C",
      },
      {
        id: "c-2",
        prompt: "Qual acorde representa o ii grau em C maior?",
        options: ["Em", "Dm", "F", "Bdim"],
        correctAnswer: "Dm",
      },
      {
        id: "c-3",
        prompt: "Qual e o V grau dominante em C maior?",
        options: ["G", "F", "Am", "E"],
        correctAnswer: "G",
      },
      {
        id: "c-4",
        prompt: "Qual e o VII grau meio-diminuto (tríade diminuta) em C maior?",
        options: ["Bdim", "Bm", "Ddim", "F#dim"],
        correctAnswer: "Bdim",
      },
      {
        id: "c-5",
        prompt: "Qual acorde representa o vi grau relativo menor em C maior?",
        options: ["Am", "Em", "Dm", "G"],
        correctAnswer: "Am",
      },
      {
        id: "c-6",
        prompt: "Qual sequencia esta correta para I-IV-V em C maior?",
        options: ["C - F - G", "C - Em - G", "C - Dm - Am", "C - G - F#m"],
        correctAnswer: "C - F - G",
      },
      {
        id: "c-7",
        prompt: "Qual e o acorde do iii grau em C maior?",
        options: ["Em", "E", "Am", "F"],
        correctAnswer: "Em",
      },
      {
        id: "c-8",
        prompt: "Qual conjunto contem somente acordes do campo harmonico de C maior?",
        options: ["C, Dm, Em, F, G, Am, Bdim", "C, D, Em, F, G, A, Bdim", "C, Dm, E, F, G, Am, Bm", "Cm, Dm, Eb, Fm, G, Ab, Bb"],
        correctAnswer: "C, Dm, Em, F, G, Am, Bdim",
      },
      {
        id: "c-9",
        prompt: "No campo harmonico de C maior, qual acorde e o IV grau?",
        options: ["F", "G", "Dm", "Am"],
        correctAnswer: "F",
      },
      {
        id: "c-10",
        prompt: "No campo harmonico de C maior, qual acorde e o vii grau?",
        options: ["Bdim", "Bm", "G", "Em"],
        correctAnswer: "Bdim",
      },
      {
        id: "c-11",
        prompt: "Qual grau corresponde ao acorde Em em C maior?",
        options: ["iii", "ii", "vi", "vii"],
        correctAnswer: "iii",
      },
      {
        id: "c-12",
        prompt: "Qual grau corresponde ao acorde Am em C maior?",
        options: ["vi", "iii", "ii", "v"],
        correctAnswer: "vi",
      },
      {
        id: "c-13",
        prompt: "Qual acorde corresponde ao grau ii em C maior?",
        options: ["Dm", "Em", "F", "G"],
        correctAnswer: "Dm",
      },
      {
        id: "c-14",
        prompt: "Qual acorde corresponde ao grau vii em C maior?",
        options: ["Bdim", "Am", "C", "Dm"],
        correctAnswer: "Bdim",
      },
      {
        id: "c-15",
        prompt: "Qual alternativa mostra corretamente I-vi-ii-V em C maior?",
        options: ["C - Am - Dm - G", "C - Em - Dm - F", "C - Am - Em - G", "C - F - Dm - Am"],
        correctAnswer: "C - Am - Dm - G",
      },
      {
        id: "c-16",
        prompt: "Em C maior, qual grau e considerado dominante?",
        options: ["V", "IV", "ii", "vi"],
        correctAnswer: "V",
      },
    ],
  },
  {
    id: "harmonic-field-d",
    title: "Campo Harmonico de D",
    description: "Perguntas sobre os acordes diatonicos da tonalidade de D maior.",
    questions: [
      {
        id: "d-1",
        prompt: "Qual e o I grau (tonica) no campo harmonico de D maior?",
        options: ["D", "A", "Em", "Bm"],
        correctAnswer: "D",
      },
      {
        id: "d-2",
        prompt: "Qual acorde representa o iii grau em D maior?",
        options: ["F#m", "Em", "G", "C#dim"],
        correctAnswer: "F#m",
      },
      {
        id: "d-3",
        prompt: "Qual e o IV grau subdominante em D maior?",
        options: ["G", "A", "E", "Bm"],
        correctAnswer: "G",
      },
      {
        id: "d-4",
        prompt: "Qual e o VII grau diminuto em D maior?",
        options: ["C#dim", "Cdim", "F#dim", "Bdim"],
        correctAnswer: "C#dim",
      },
      {
        id: "d-5",
        prompt: "Qual acorde representa o ii grau em D maior?",
        options: ["Em", "G", "Bm", "A"],
        correctAnswer: "Em",
      },
      {
        id: "d-6",
        prompt: "Qual e o V grau dominante em D maior?",
        options: ["A", "G", "F#m", "E"],
        correctAnswer: "A",
      },
      {
        id: "d-7",
        prompt: "Qual e o vi grau relativo menor em D maior?",
        options: ["Bm", "F#m", "Em", "C#dim"],
        correctAnswer: "Bm",
      },
      {
        id: "d-8",
        prompt: "Qual conjunto contem somente acordes do campo harmonico de D maior?",
        options: ["D, Em, F#m, G, A, Bm, C#dim", "D, Em, F, G, A, Bm, C#dim", "D, E, F#m, G, A, B, C#dim", "Dm, Em, F, Gm, A, Bb, C"],
        correctAnswer: "D, Em, F#m, G, A, Bm, C#dim",
      },
      {
        id: "d-9",
        prompt: "No campo harmonico de D maior, qual acorde e o IV grau?",
        options: ["G", "A", "Em", "Bm"],
        correctAnswer: "G",
      },
      {
        id: "d-10",
        prompt: "No campo harmonico de D maior, qual acorde e o iii grau?",
        options: ["F#m", "Em", "A", "C#dim"],
        correctAnswer: "F#m",
      },
      {
        id: "d-11",
        prompt: "Qual grau corresponde ao acorde Bm em D maior?",
        options: ["vi", "iii", "ii", "vii"],
        correctAnswer: "vi",
      },
      {
        id: "d-12",
        prompt: "Qual grau corresponde ao acorde C#dim em D maior?",
        options: ["vii", "vi", "iii", "ii"],
        correctAnswer: "vii",
      },
      {
        id: "d-13",
        prompt: "Qual acorde corresponde ao grau V em D maior?",
        options: ["A", "G", "F#m", "Em"],
        correctAnswer: "A",
      },
      {
        id: "d-14",
        prompt: "Qual acorde corresponde ao grau ii em D maior?",
        options: ["Em", "F#m", "G", "Bm"],
        correctAnswer: "Em",
      },
      {
        id: "d-15",
        prompt: "Qual alternativa mostra corretamente I-vi-ii-V em D maior?",
        options: ["D - Bm - Em - A", "D - F#m - Em - G", "D - Bm - F#m - A", "D - G - Em - Bm"],
        correctAnswer: "D - Bm - Em - A",
      },
      {
        id: "d-16",
        prompt: "Em D maior, qual grau e a tonica?",
        options: ["I", "V", "IV", "vi"],
        correctAnswer: "I",
      },
    ],
  },
  {
    id: "degrees-only",
    title: "Somente Graus",
    description: "Treino focado apenas em graus harmonicos (I a VII).",
    questions: [
      {
        id: "g-1",
        prompt: "Qual grau representa a tonica?",
        options: ["I", "V", "IV", "vi"],
        correctAnswer: "I",
      },
      {
        id: "g-2",
        prompt: "Qual grau e conhecido como dominante?",
        options: ["V", "ii", "IV", "iii"],
        correctAnswer: "V",
      },
      {
        id: "g-3",
        prompt: "Qual grau e conhecido como subdominante?",
        options: ["IV", "I", "V", "vi"],
        correctAnswer: "IV",
      },
      {
        id: "g-4",
        prompt: "Em uma tonalidade maior, qual e o relativo menor da tonica?",
        options: ["vi", "iii", "ii", "vii"],
        correctAnswer: "vi",
      },
      {
        id: "g-5",
        prompt: "Qual grau normalmente gera maior tensao antes de resolver na tonica?",
        options: ["V", "I", "vi", "ii"],
        correctAnswer: "V",
      },
      {
        id: "g-6",
        prompt: "Qual grau corresponde ao acorde diminuto diatonico em campo harmonico maior?",
        options: ["vii", "ii", "iii", "vi"],
        correctAnswer: "vii",
      },
      {
        id: "g-7",
        prompt: "Na progressao I-IV-V-I, qual e o terceiro acorde?",
        options: ["V", "IV", "I", "ii"],
        correctAnswer: "V",
      },
      {
        id: "g-8",
        prompt: "Qual grau geralmente aparece como preparacao para o V em progressao funcional?",
        options: ["ii", "I", "vi", "iii"],
        correctAnswer: "ii",
      },
      {
        id: "g-9",
        prompt: "Qual grau tem funcao tonica secundaria junto com o I?",
        options: ["vi", "V", "IV", "vii"],
        correctAnswer: "vi",
      },
      {
        id: "g-10",
        prompt: "Em numeros romanos, qual grau vem logo apos o iii?",
        options: ["IV", "V", "ii", "vi"],
        correctAnswer: "IV",
      },
      {
        id: "g-11",
        prompt: "Qual sequencia representa uma cadencia autentica basica?",
        options: ["V - I", "IV - I", "ii - iii", "vi - IV"],
        correctAnswer: "V - I",
      },
      {
        id: "g-12",
        prompt: "Qual grau corresponde ao supertonico?",
        options: ["ii", "iii", "IV", "vii"],
        correctAnswer: "ii",
      },
    ],
  },
];
