export const quizzes = [
  {
    id: "harmonic-field-c",
    title: "Campo Harmonico de C",
    description: "Perguntas sobre os acordes diatonicos da tonalidade de C maior.",
    questions: [
      {
        id: "c-1",
        prompt: "Qual e o I grau (tonica) no campo harmonico de C maior?",
        options: ["C", "Dm", "G", "Am"],
        correctAnswer: "C",
      },
      {
        id: "c-2",
        prompt: "Qual acorde representa o ii grau em C maior?",
        options: ["Em", "Dm", "F", "Bdim"],
        correctAnswer: "Dm",
      },
      {
        id: "c-3",
        prompt: "Qual e o V grau dominante em C maior?",
        options: ["G", "F", "Am", "E"],
        correctAnswer: "G",
      },
      {
        id: "c-4",
        prompt: "Qual e o VII grau meio-diminuto (tríade diminuta) em C maior?",
        options: ["Bdim", "Bm", "Ddim", "F#dim"],
        correctAnswer: "Bdim",
      },
      {
        id: "c-5",
        prompt: "Qual acorde representa o vi grau relativo menor em C maior?",
        options: ["Am", "Em", "Dm", "G"],
        correctAnswer: "Am",
      },
      {
        id: "c-6",
        prompt: "Qual sequencia esta correta para I-IV-V em C maior?",
        options: ["C - F - G", "C - Em - G", "C - Dm - Am", "C - G - F#m"],
        correctAnswer: "C - F - G",
      },
      {
        id: "c-7",
        prompt: "Qual e o acorde do iii grau em C maior?",
        options: ["Em", "E", "Am", "F"],
        correctAnswer: "Em",
      },
      {
        id: "c-8",
        prompt: "Qual conjunto contem somente acordes do campo harmonico de C maior?",
        options: ["C, Dm, Em, F, G, Am, Bdim", "C, D, Em, F, G, A, Bdim", "C, Dm, E, F, G, Am, Bm", "Cm, Dm, Eb, Fm, G, Ab, Bb"],
        correctAnswer: "C, Dm, Em, F, G, Am, Bdim",
      },
      {
        id: "c-9",
        prompt: "No campo harmonico de C maior, qual acorde e o IV grau?",
        options: ["F", "G", "Dm", "Am"],
        correctAnswer: "F",
      },
      {
        id: "c-10",
        prompt: "No campo harmonico de C maior, qual acorde e o vii grau?",
        options: ["Bdim", "Bm", "G", "Em"],
        correctAnswer: "Bdim",
      },
      {
        id: "c-11",
        prompt: "Qual grau corresponde ao acorde Em em C maior?",
        options: ["iii", "ii", "vi", "vii"],
        correctAnswer: "iii",
      },
      {
        id: "c-12",
        prompt: "Qual grau corresponde ao acorde Am em C maior?",
        options: ["vi", "iii", "ii", "v"],
        correctAnswer: "vi",
      },
      {
        id: "c-13",
        prompt: "Qual acorde corresponde ao grau ii em C maior?",
        options: ["Dm", "Em", "F", "G"],
        correctAnswer: "Dm",
      },
      {
        id: "c-14",
        prompt: "Qual acorde corresponde ao grau vii em C maior?",
        options: ["Bdim", "Am", "C", "Dm"],
        correctAnswer: "Bdim",
      },
      {
        id: "c-15",
        prompt: "Qual alternativa mostra corretamente I-vi-ii-V em C maior?",
        options: ["C - Am - Dm - G", "C - Em - Dm - F", "C - Am - Em - G", "C - F - Dm - Am"],
        correctAnswer: "C - Am - Dm - G",
      },
      {
        id: "c-16",
        prompt: "Em C maior, qual grau e considerado dominante?",
        options: ["V", "IV", "ii", "vi"],
        correctAnswer: "V",
      },
    ],
  },
  {
    id: "harmonic-field-d",
    title: "Campo Harmonico de D",
    description: "Perguntas sobre os acordes diatonicos da tonalidade de D maior.",
    questions: [
      {
        id: "d-1",
        prompt: "Qual e o I grau (tonica) no campo harmonico de D maior?",
        options: ["D", "A", "Em", "Bm"],
        correctAnswer: "D",
      },
      {
        id: "d-2",
        prompt: "Qual acorde representa o iii grau em D maior?",
        options: ["F#m", "Em", "G", "C#dim"],
        correctAnswer: "F#m",
      },
      {
        id: "d-3",
        prompt: "Qual e o IV grau subdominante em D maior?",
        options: ["G", "A", "E", "Bm"],
        correctAnswer: "G",
      },
      {
        id: "d-4",
        prompt: "Qual e o VII grau diminuto em D maior?",
        options: ["C#dim", "Cdim", "F#dim", "Bdim"],
        correctAnswer: "C#dim",
      },
      {
        id: "d-5",
        prompt: "Qual acorde representa o ii grau em D maior?",
        options: ["Em", "G", "Bm", "A"],
        correctAnswer: "Em",
      },
      {
        id: "d-6",
        prompt: "Qual e o V grau dominante em D maior?",
        options: ["A", "G", "F#m", "E"],
        correctAnswer: "A",
      },
      {
        id: "d-7",
        prompt: "Qual e o vi grau relativo menor em D maior?",
        options: ["Bm", "F#m", "Em", "C#dim"],
        correctAnswer: "Bm",
      },
      {
        id: "d-8",
        prompt: "Qual conjunto contem somente acordes do campo harmonico de D maior?",
        options: ["D, Em, F#m, G, A, Bm, C#dim", "D, Em, F, G, A, Bm, C#dim", "D, E, F#m, G, A, B, C#dim", "Dm, Em, F, Gm, A, Bb, C"],
        correctAnswer: "D, Em, F#m, G, A, Bm, C#dim",
      },
      {
        id: "d-9",
        prompt: "No campo harmonico de D maior, qual acorde e o IV grau?",
        options: ["G", "A", "Em", "Bm"],
        correctAnswer: "G",
      },
      {
        id: "d-10",
        prompt: "No campo harmonico de D maior, qual acorde e o iii grau?",
        options: ["F#m", "Em", "A", "C#dim"],
        correctAnswer: "F#m",
      },
      {
        id: "d-11",
        prompt: "Qual grau corresponde ao acorde Bm em D maior?",
        options: ["vi", "iii", "ii", "vii"],
        correctAnswer: "vi",
      },
      {
        id: "d-12",
        prompt: "Qual grau corresponde ao acorde C#dim em D maior?",
        options: ["vii", "vi", "iii", "ii"],
        correctAnswer: "vii",
      },
      {
        id: "d-13",
        prompt: "Qual acorde corresponde ao grau V em D maior?",
        options: ["A", "G", "F#m", "Em"],
        correctAnswer: "A",
      },
      {
        id: "d-14",
        prompt: "Qual acorde corresponde ao grau ii em D maior?",
        options: ["Em", "F#m", "G", "Bm"],
        correctAnswer: "Em",
      },
      {
        id: "d-15",
        prompt: "Qual alternativa mostra corretamente I-vi-ii-V em D maior?",
        options: ["D - Bm - Em - A", "D - F#m - Em - G", "D - Bm - F#m - A", "D - G - Em - Bm"],
        correctAnswer: "D - Bm - Em - A",
      },
      {
        id: "d-16",
        prompt: "Em D maior, qual grau e a tonica?",
        options: ["I", "V", "IV", "vi"],
        correctAnswer: "I",
      },
    ],
  },
  {
    id: "degrees-only",
    title: "Somente Graus",
    description: "Treino focado apenas em graus harmonicos (I a VII).",
    questions: [
      {
        id: "g-1",
        prompt: "Qual grau representa a tonica?",
        options: ["I", "V", "IV", "vi"],
        correctAnswer: "I",
      },
      {
        id: "g-2",
        prompt: "Qual grau e conhecido como dominante?",
        options: ["V", "ii", "IV", "iii"],
        correctAnswer: "V",
      },
      {
        id: "g-3",
        prompt: "Qual grau e conhecido como subdominante?",
        options: ["IV", "I", "V", "vi"],
        correctAnswer: "IV",
      },
      {
        id: "g-4",
        prompt: "Em uma tonalidade maior, qual e o relativo menor da tonica?",
        options: ["vi", "iii", "ii", "vii"],
        correctAnswer: "vi",
      },
      {
        id: "g-5",
        prompt: "Qual grau normalmente gera maior tensao antes de resolver na tonica?",
        options: ["V", "I", "vi", "ii"],
        correctAnswer: "V",
      },
      {
        id: "g-6",
        prompt: "Qual grau corresponde ao acorde diminuto diatonico em campo harmonico maior?",
        options: ["vii", "ii", "iii", "vi"],
        correctAnswer: "vii",
      },
      {
        id: "g-7",
        prompt: "Na progressao I-IV-V-I, qual e o terceiro acorde?",
        options: ["V", "IV", "I", "ii"],
        correctAnswer: "V",
      },
      {
        id: "g-8",
        prompt: "Qual grau geralmente aparece como preparacao para o V em progressao funcional?",
        options: ["ii", "I", "vi", "iii"],
        correctAnswer: "ii",
      },
      {
        id: "g-9",
        prompt: "Qual grau tem funcao tonica secundaria junto com o I?",
        options: ["vi", "V", "IV", "vii"],
        correctAnswer: "vi",
      },
      {
        id: "g-10",
        prompt: "Em numeros romanos, qual grau vem logo apos o iii?",
        options: ["IV", "V", "ii", "vi"],
        correctAnswer: "IV",
      },
      {
        id: "g-11",
        prompt: "Qual sequencia representa uma cadencia autentica basica?",
        options: ["V - I", "IV - I", "ii - iii", "vi - IV"],
        correctAnswer: "V - I",
      },
      {
        id: "g-12",
        prompt: "Qual grau corresponde ao supertonico?",
        options: ["ii", "iii", "IV", "vii"],
        correctAnswer: "ii",
      },
    ],
  },
  {
    id: "harmonic-field-e",
    title: "Campo Harmonico de E",
    description: "Perguntas sobre os acordes diatonicos da tonalidade de E maior.",
    questions: [
      {
        id: "e-1",
        prompt: "Qual e o I grau (tonica) no campo harmonico de E maior?",
        options: ["E", "B", "F#m", "C#m"],
        correctAnswer: "E",
      },
      {
        id: "e-2",
        prompt: "Qual acorde representa o ii grau em E maior?",
        options: ["F#m", "G#m", "A", "D#dim"],
        correctAnswer: "F#m",
      },
      {
        id: "e-3",
        prompt: "Qual e o V grau dominante em E maior?",
        options: ["B", "A", "C#m", "F#"],
        correctAnswer: "B",
      },
      {
        id: "e-4",
        prompt: "Qual e o VII grau diminuto em E maior?",
        options: ["D#dim", "Ddim", "G#dim", "C#dim"],
        correctAnswer: "D#dim",
      },
      {
        id: "e-5",
        prompt: "Qual acorde representa o vi grau relativo menor em E maior?",
        options: ["C#m", "G#m", "F#m", "B"],
        correctAnswer: "C#m",
      },
      {
        id: "e-6",
        prompt: "Qual sequencia esta correta para I-IV-V em E maior?",
        options: ["E - A - B", "E - G#m - B", "E - F#m - C#m", "E - B - A#m"],
        correctAnswer: "E - A - B",
      },
      {
        id: "e-7",
        prompt: "Qual e o acorde do iii grau em E maior?",
        options: ["G#m", "G#", "C#m", "A"],
        correctAnswer: "G#m",
      },
      {
        id: "e-8",
        prompt: "Qual conjunto contem somente acordes do campo harmonico de E maior?",
        options: ["E, F#m, G#m, A, B, C#m, D#dim", "E, F#m, G#, A, B, C#m, D#dim", "E, F#m, G#m, A, B, C#, D#dim", "Em, F#m, G, Am, B, C, D"],
        correctAnswer: "E, F#m, G#m, A, B, C#m, D#dim",
      },
      {
        id: "e-9",
        prompt: "No campo harmonico de E maior, qual acorde e o IV grau?",
        options: ["A", "B", "F#m", "C#m"],
        correctAnswer: "A",
      },
      {
        id: "e-10",
        prompt: "No campo harmonico de E maior, qual acorde e o vii grau?",
        options: ["D#dim", "D#m", "B", "G#m"],
        correctAnswer: "D#dim",
      },
      {
        id: "e-11",
        prompt: "Qual grau corresponde ao acorde G#m em E maior?",
        options: ["iii", "ii", "vi", "vii"],
        correctAnswer: "iii",
      },
      {
        id: "e-12",
        prompt: "Qual grau corresponde ao acorde C#m em E maior?",
        options: ["vi", "iii", "ii", "v"],
        correctAnswer: "vi",
      },
      {
        id: "e-13",
        prompt: "Qual acorde corresponde ao grau ii em E maior?",
        options: ["F#m", "G#m", "A", "B"],
        correctAnswer: "F#m",
      },
      {
        id: "e-14",
        prompt: "Qual acorde corresponde ao grau vii em E maior?",
        options: ["D#dim", "C#m", "E", "F#m"],
        correctAnswer: "D#dim",
      },
      {
        id: "e-15",
        prompt: "Qual alternativa mostra corretamente I-vi-ii-V em E maior?",
        options: ["E - C#m - F#m - B", "E - G#m - F#m - A", "E - C#m - G#m - B", "E - A - F#m - C#m"],
        correctAnswer: "E - C#m - F#m - B",
      },
      {
        id: "e-16",
        prompt: "Em E maior, qual grau e considerado dominante?",
        options: ["V", "IV", "ii", "vi"],
        correctAnswer: "V",
      },
    ],
  },
  {
    id: "harmonic-field-cde-mixed",
    title: "Campo Harmonico Misturado (C, D e E)",
    description: "Perguntas misturadas sobre os campos harmonicos de C maior, D maior e E maior.",
    questions: [
      {
        id: "cde-1",
        prompt: "Em C maior, qual e o vi grau?",
        options: ["Am", "Em", "Dm", "G"],
        correctAnswer: "Am",
      },
      {
        id: "cde-2",
        prompt: "Em D maior, qual e o ii grau?",
        options: ["Em", "F#m", "G", "Bm"],
        correctAnswer: "Em",
      },
      {
        id: "cde-3",
        prompt: "Em E maior, qual e o V grau?",
        options: ["B", "A", "C#m", "F#m"],
        correctAnswer: "B",
      },
      {
        id: "cde-4",
        prompt: "Qual alternativa contem os acordes I-IV-V de C maior?",
        options: ["C - F - G", "C - Dm - G", "C - Em - G", "C - Am - F"],
        correctAnswer: "C - F - G",
      },
      {
        id: "cde-5",
        prompt: "Qual e o vii grau em D maior?",
        options: ["C#dim", "Bdim", "D#dim", "F#dim"],
        correctAnswer: "C#dim",
      },
      {
        id: "cde-6",
        prompt: "Qual acorde e o iii grau em E maior?",
        options: ["G#m", "F#m", "C#m", "A"],
        correctAnswer: "G#m",
      },
      {
        id: "cde-7",
        prompt: "Qual conjunto esta correto para C maior?",
        options: ["C, Dm, Em, F, G, Am, Bdim", "C, D, Em, F, G, A, Bdim", "C, Dm, E, F, G, Am, Bm", "Cm, Dm, Eb, F, G, Ab, Bb"],
        correctAnswer: "C, Dm, Em, F, G, Am, Bdim",
      },
      {
        id: "cde-8",
        prompt: "Qual conjunto esta correto para D maior?",
        options: ["D, Em, F#m, G, A, Bm, C#dim", "D, Em, F, G, A, Bm, C#dim", "D, E, F#m, G, A, B, C#dim", "Dm, Em, F, Gm, A, Bb, C"],
        correctAnswer: "D, Em, F#m, G, A, Bm, C#dim",
      },
      {
        id: "cde-9",
        prompt: "Qual conjunto esta correto para E maior?",
        options: ["E, F#m, G#m, A, B, C#m, D#dim", "E, F#m, G#, A, B, C#m, D#dim", "E, F#m, G#m, A, B, C#, D#dim", "Em, F#m, G, A, B, C, D"],
        correctAnswer: "E, F#m, G#m, A, B, C#m, D#dim",
      },
      {
        id: "cde-10",
        prompt: "Em C maior, qual acorde corresponde ao grau ii?",
        options: ["Dm", "Em", "F", "Am"],
        correctAnswer: "Dm",
      },
      {
        id: "cde-11",
        prompt: "Em D maior, qual acorde corresponde ao grau vi?",
        options: ["Bm", "F#m", "Em", "G"],
        correctAnswer: "Bm",
      },
      {
        id: "cde-12",
        prompt: "Em E maior, qual acorde corresponde ao grau IV?",
        options: ["A", "B", "F#m", "C#m"],
        correctAnswer: "A",
      },
      {
        id: "cde-13",
        prompt: "Qual progressao I-vi-ii-V esta correta em D maior?",
        options: ["D - Bm - Em - A", "D - F#m - Em - G", "D - Bm - F#m - A", "D - G - Em - Bm"],
        correctAnswer: "D - Bm - Em - A",
      },
      {
        id: "cde-14",
        prompt: "Qual progressao I-vi-ii-V esta correta em E maior?",
        options: ["E - C#m - F#m - B", "E - G#m - F#m - A", "E - C#m - G#m - B", "E - A - F#m - C#m"],
        correctAnswer: "E - C#m - F#m - B",
      },
      {
        id: "cde-15",
        prompt: "Em qual dessas tonalidades o vii grau e Bdim?",
        options: ["C maior", "D maior", "E maior", "Nenhuma"],
        correctAnswer: "C maior",
      },
      {
        id: "cde-16",
        prompt: "Em qual dessas tonalidades o vii grau e D#dim?",
        options: ["E maior", "D maior", "C maior", "Nenhuma"],
        correctAnswer: "E maior",
      },
      {
        id: "cde-17",
        prompt: "Em C maior, qual e o iii grau?",
        options: ["Em", "Dm", "Am", "G"],
        correctAnswer: "Em",
      },
      {
        id: "cde-18",
        prompt: "Em D maior, qual e o IV grau?",
        options: ["G", "A", "Em", "F#m"],
        correctAnswer: "G",
      },
      {
        id: "cde-19",
        prompt: "Em E maior, qual e o vi grau?",
        options: ["C#m", "G#m", "F#m", "B"],
        correctAnswer: "C#m",
      },
      {
        id: "cde-20",
        prompt: "Qual dessas tonalidades tem A como IV grau?",
        options: ["E maior", "D maior", "C maior", "Nenhuma"],
        correctAnswer: "E maior",
      },
      {
        id: "cde-21",
        prompt: "Qual dessas tonalidades tem G como V grau?",
        options: ["C maior", "D maior", "E maior", "Nenhuma"],
        correctAnswer: "C maior",
      },
      {
        id: "cde-22",
        prompt: "Em qual tonalidade Bm e o vi grau?",
        options: ["D maior", "C maior", "E maior", "Nenhuma"],
        correctAnswer: "D maior",
      },
      {
        id: "cde-23",
        prompt: "Qual progressao I-IV-V esta correta em E maior?",
        options: ["E - A - B", "E - F#m - B", "E - G#m - A", "E - C#m - B"],
        correctAnswer: "E - A - B",
      },
      {
        id: "cde-24",
        prompt: "Em qual tonalidade C#m e o vi grau?",
        options: ["E maior", "D maior", "C maior", "Nenhuma"],
        correctAnswer: "E maior",
      },
    ],
  },
  {
    id: "harmonic-field-cde-advanced",
    title: "Campo Harmonico Avancado (C, D e E)",
    description: "Perguntas mais dificeis misturando analise funcional e graus entre C, D e E maiores.",
    questions: [
      {
        id: "cde-adv-1",
        prompt: "Qual alternativa traz corretamente os vii graus de C, D e E maiores (nessa ordem)?",
        options: ["Bdim, C#dim, D#dim", "Bdim, Ddim, D#dim", "Bdim, C#dim, Ebdim", "Cdim, C#dim, D#dim"],
        correctAnswer: "Bdim, C#dim, D#dim",
      },
      {
        id: "cde-adv-2",
        prompt: "Em C maior, qual progressao expressa claramente pre-dominante -> dominante -> tonica?",
        options: ["Dm - G - C", "Am - F - C", "Em - Am - Dm", "C - G - Dm"],
        correctAnswer: "Dm - G - C",
      },
      {
        id: "cde-adv-3",
        prompt: "Qual progressao representa ii-V-I em E maior?",
        options: ["F#m - B - E", "C#m - F#m - B", "A - B - E", "G#m - C#m - F#m"],
        correctAnswer: "F#m - B - E",
      },
      {
        id: "cde-adv-4",
        prompt: "Em D maior, qual acorde cumpre funcao de tonica secundaria junto do I?",
        options: ["Bm", "A", "G", "Em"],
        correctAnswer: "Bm",
      },
      {
        id: "cde-adv-5",
        prompt: "Qual conjunto contem apenas acordes de funcao predominante em C maior?",
        options: ["Dm e F", "G e Bdim", "C e Am", "Em e Bdim"],
        correctAnswer: "Dm e F",
      },
      {
        id: "cde-adv-6",
        prompt: "Em qual tonalidade o acorde G#m e simultaneamente iii grau?",
        options: ["E maior", "D maior", "C maior", "Nenhuma"],
        correctAnswer: "E maior",
      },
      {
        id: "cde-adv-7",
        prompt: "Qual alternativa descreve corretamente I-iii-vi em D maior?",
        options: ["D - F#m - Bm", "D - Em - Bm", "D - F#m - Em", "D - G - Bm"],
        correctAnswer: "D - F#m - Bm",
      },
      {
        id: "cde-adv-8",
        prompt: "Em C maior, qual acorde compartilha 2 notas com a tonica C (C-E-G)?",
        options: ["Am", "Dm", "Bdim", "F"],
        correctAnswer: "Am",
      },
      {
        id: "cde-adv-9",
        prompt: "Qual opcao contem os relativos menores de C, D e E maiores (nessa ordem)?",
        options: ["Am, Bm, C#m", "Am, F#m, C#m", "Em, Bm, G#m", "Am, Bm, G#m"],
        correctAnswer: "Am, Bm, C#m",
      },
      {
        id: "cde-adv-10",
        prompt: "Se em E maior o V e B, qual e o ii que prepara esse dominante?",
        options: ["F#m", "C#m", "A", "G#m"],
        correctAnswer: "F#m",
      },
      {
        id: "cde-adv-11",
        prompt: "Qual alternativa esta correta para as trincas (ii, V, I) em C e D maiores?",
        options: ["Dm-G-C e Em-A-D", "Em-G-C e F#m-A-D", "Dm-F-C e Em-G-D", "Am-G-C e Bm-A-D"],
        correctAnswer: "Dm-G-C e Em-A-D",
      },
      {
        id: "cde-adv-12",
        prompt: "Em D maior, qual acorde diatonico tem funcao dominante mais forte?",
        options: ["A", "Em", "Bm", "G"],
        correctAnswer: "A",
      },
      {
        id: "cde-adv-13",
        prompt: "Qual comparacao esta correta sobre o iii grau?",
        options: ["C: Em | D: F#m | E: G#m", "C: Em | D: G | E: G#m", "C: Dm | D: F#m | E: A", "C: Em | D: F#m | E: F#m"],
        correctAnswer: "C: Em | D: F#m | E: G#m",
      },
      {
        id: "cde-adv-14",
        prompt: "Em C maior, qual progressao tende a soar como expansao de tonica antes do dominante?",
        options: ["C - Em - Am - G", "Dm - F - G - C", "G - F - Em - Dm", "C - Dm - Em - F"],
        correctAnswer: "C - Em - Am - G",
      },
      {
        id: "cde-adv-15",
        prompt: "Qual afirmacao e verdadeira sobre os graus IV em C, D e E maiores?",
        options: ["Sao F, G e A respectivamente", "Sao G, A e B respectivamente", "Sao F, G e G# respectivamente", "Sao Fm, Gm e Am respectivamente"],
        correctAnswer: "Sao F, G e A respectivamente",
      },
      {
        id: "cde-adv-16",
        prompt: "Qual sequencia representa tres cadencias autenticas (V-I) em C, D e E maiores?",
        options: ["G-C | A-D | B-E", "F-C | G-D | A-E", "G-C | G-D | B-E", "G-C | A-D | A-E"],
        correctAnswer: "G-C | A-D | B-E",
      },
    ],
  },
];
